import React from 'react'
import s from './AttributionsModal.module.css'
import { FocusTrapModal } from './FocusTrapModal'

interface Attribution {
  name: string
  version: string
  license: string
  url?: string
}

interface LicensesDoc {
  scope?: string
  components: Attribution[]
}

/**
 * Open-source attributions for the web-client's production dependencies.
 * The list is served as a static asset (`public/licenses.json`), generated by
 * `licensing/licenses.py` from the same closure the licence gate enforces — so
 * it can't drift from what is released. Surfacing it discharges the MIT/BSD
 * attribution duty once the frontend is distributed (published image / SaaS).
 */
export const AttributionsModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
  const [doc, setDoc] = React.useState<LicensesDoc | null>(null)
  const [failed, setFailed] = React.useState(false)

  React.useEffect(() => {
    let active = true
    fetch(`${import.meta.env.BASE_URL}licenses.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then((data: LicensesDoc) => {
        if (active) setDoc(data)
      })
      .catch(() => {
        if (active) setFailed(true)
      })
    return () => {
      active = false
    }
  }, [])

  return (
    <FocusTrapModal
      className={s.backdrop}
      onClose={onClose}
      onBackdropClick={onClose}
      label="Open-source licences"
    >
      <div className={s.card} onClick={(e) => e.stopPropagation()}>
        <div className={s.header}>
          <h2 className={s.title}>Open-source licences</h2>
          <button type="button" className={s.close} onClick={onClose} aria-label="Close">
            ×
          </button>
        </div>
        <p className={s.intro}>
          Swarpius is built on the open-source components below, each under its own licence.
        </p>
        {failed ? (
          <p className={s.status}>Could not load licence information.</p>
        ) : !doc ? (
          <p className={s.status}>Loading…</p>
        ) : (
          <ul className={s.list}>
            {doc.components.map((c) => (
              <li key={`${c.name}@${c.version}`} className={s.item}>
                <span className={s.name}>
                  {c.url ? (
                    <a href={c.url} target="_blank" rel="noopener noreferrer">
                      {c.name}
                    </a>
                  ) : (
                    c.name
                  )}
                </span>
                <span className={s.version}>{c.version}</span>
                <span className={s.license}>{c.license}</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </FocusTrapModal>
  )
}
